apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: 0.8.26
  labels:
    app: hello
  name: hello
spec:
  replicas: 9
  selector:
    matchLabels:
      app: hello
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.26
        name: hello-http
        env:
          - name: PORT
            value: "80"
          - name: MSG
            valueFrom:
              configMapKeyRef:
                name: hello
                key: MSG
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: hello
                key: VERSION
        envFrom:
          - secretRef:
              name: hello
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 2
          failureThreshold: 2
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 4
          failureThreshold: 4
          timeoutSeconds: 1
        resources: {}
status: {}
