apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.26
        name: hello-http
        env:
          - name: PORT
            value: "80"
          - name: MSG
            valueFrom:
              configMapKeyRef:
                name: hello
                key: MSG
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: hello
                key: VERSION
        envFrom:
          - secretRef:
              name: hello
        ports:
          - name: http
            containerPort: 80
        resources: {}
status: {}
