apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http
  name: http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http
status:
  loadBalancer: {}
