apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-deploy
  name: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-pod
  template:
    metadata:
      labels:
        app: http-pod
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
          - name: http
            containerPort: 80
      - image: php:8.2-fpm
        name: php
