apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http
  name: http
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
    nodePort: 32000
  selector:
    app: http
  type: NodePort
status:
  loadBalancer: {}
