apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http
  name: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
          - name: http
            containerPort: 80
      - image: php:8.2-fpm
        name: php
        envFrom:
          - configMapRef:
              name: http
            prefix: bob_
        env:
          - name: STAGE
            value: Kubernetes
          - name: IPPOD
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOUR
            valueFrom:
              configMapKeyRef:
                name: http
                key: JOUR
