apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.8
        name: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD_FILE
            value: /tmp/mariadb/password
        volumeMounts:
          - name: mariadb-pw
            mountPath: /tmp/mariadb
          - name: datadir
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-pw
          secret:
            secretName: mariadb
            defaultMode: 0400
        - name: datadir
          nfs:
            server: 172.18.0.1
            path: /datadir
