apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: allpod-stage
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allpod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
