apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: allview-bob
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allview
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
